---
version: "3.8"
services:
  lifechanging_ml:
    build: ./1_Simplest/.
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

networks:
  backend:
    driver: bridge