FROM python:3.7.8-buster

COPY ./ /app

RUN apt-get install -y default-libmysqlclient-dev

RUN pip install flask scikit-learn sqlalchemy pandas mysqlclient

EXPOSE 80

ENTRYPOINT cd /app && python ./app.py
